
query ($auth0Id:String!) {
  getUserByAuth0Id(auth0Id: $auth0Id) {
    id
    auth0Id
    email
  }
}




mutation ($auth0Id: String!, $email: Email!, $name: String!, $dateOfBirth: Date!, $socialURLs: InputSocialURLs) {
  createUser(auth0Id: $auth0Id, email: $email, name: $name, dateOfBirth: $dateOfBirth, socialURLs: $socialURLs) {
    id
    auth0Id
		email
    name
    dateOfBirth
    socialURLs {
      github
      linkedin
      facebook
      twitter
    }
  }
}
